pipeline {
    agent any

    stages {

        stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                      npm ci 
                      npm test

                    '''
                }
            
            }
        }
    }
}