pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            steps {
                dir('backtracker-backend') {
                    go test -v ./...
                }
            }
        }
    }
}