pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            steps {
                dir('backtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}